import esbuild from "esbuild";
import { rename } from "node:fs/promises";
import { builtinModules } from 'node:module';
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// esbuild will always output a `main.css` file after the build step where it bundles the CSS modules classes,
// because our entry point is `main.ts`. 
// There is no way to specify a different pathname in this config.
// Obsidian however needs it to be `styles.css`. So we have this code run `onEnd`, meaning after every build. 
const renameCssPlugin = {
	name: "rename-css",
	setup(build) {
		build.onEnd(async () => {
			try {
				await rename("main.css", "styles.css");
			} catch {
				// No CSS output this build.
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	loader: { ".module.css": "local-css" },
	plugins: [renameCssPlugin],
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
